name: Python Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.13"
          - "3.12"
          - "3.11"
          - "3.10"
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-15-intel, macos-latest]

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        working-directory: python
        run: uv sync --all-extras --dev

      - name: Pytest
        working-directory: python
        run: |
          uv run python --version
          uv run pytest
